SELECT * from IBMUSER.EMP;
SELECT LASTNAME,EMPNO,PHONENO from IBMUSER.EMP;
SELECT DEPTNAME, DEPTNO from IBMUSER.DEPT;
SELECT FIRSTNME from IBMUSER.EMP WHERE JOB = 'MANAGER';
SELECT COUNT(*) from IBMUSER.EMP;
SELECT COUNT(*) from IBMUSER.EMP WHERE JOB = 'MANAGER';
SELECT COUNT(*) AS NUM_EMPLOYEES from IBMUSER.EMP;
SELECT DEPTNAME, COUNT(EMPNO)
        from IBMUSER.DEPT D, IBMUSER.EMP E
        WHERE D.DEPTNO = E.WORKDEPT
        GROUP BY DEPTNAME
        ORDER BY DEPTNAME;
SELECT MAX(SALARY) SAL from IBMUSER.EMP;